version: '3.8'
services:

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8002:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - dynamodb-net

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    networks:
      - dynamodb-net
    depends_on:
      - dynamodb

networks:
  dynamodb-net:
    name: dynamodb-net
