name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build
      run: make compile

    - name: Test
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: DogCow
        AWS_SECRET_ACCESS_KEY: Moof
      run: make test
