name: Release

on:
  release:
    types:
      - published


jobs:
  release-linux-windows:
    name: Release for Linux and Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
    steps:

      - uses: actions/checkout@v4

      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: go.mod
          project_path: "./cmd/"
          extra_files: README.md LICENSE
          md5sum: FALSE
          sha256sum: FALSE
