name: Release

on:
  release:
    types:
      - published


permissions:
  contents: write


jobs:
  release-linux-windows:
    name: Release for Linux and Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
    steps:

      - uses: actions/checkout@v5

      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: go.mod
          project_path: "./cmd/"
          extra_files: README.md LICENSE
          md5sum: FALSE
          sha256sum: FALSE


  release-macos:
    name: Release for macOS
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Compile ARM64
        run: |
          GOOS=darwin GOARCH=arm64 make compile
          mv ./delete-dynamodb-items ./delete-dynamodb-items-arm64

      - name: Compile AMD64
        run: |
          GOOS=darwin GOARCH=amd64 make compile
          mv ./delete-dynamodb-items ./delete-dynamodb-items-amd64

      - name: Universal binary
        run: lipo -create -output delete-dynamodb-items ./delete-dynamodb-items-arm64 ./delete-dynamodb-items-amd64

      - uses: apple-actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - uses: halprin/macos-sign-package-notarize@v2
        with:
          path-to-binaries: ./delete-dynamodb-items
          signing-identity: ${{ secrets.SIGNING_IDENTITY }}
          app-store-connect-key: ${{ secrets.MACOS_APP_STORE_CONNECT_KEY }}
          app-store-connect-key-id: ${{ secrets.MACOS_APP_STORE_CONNECT_KEY_ID }}
          app-store-connect-issuer-id: ${{ secrets.MACOS_APP_STORE_CONNECT_ISSUER_ID }}
          archive-files: ./delete-dynamodb-items README.md LICENSE
          archive-disk-name: Delete DynamoDB Items
          archive-file-path: ./delete-dynamodb-items-${{ github.event.release.tag_name }}-macos.dmg

      - name: Upload Release Asset
        run: gh release upload ${{ github.event.release.tag_name }} ./delete-dynamodb-items-${{ github.event.release.tag_name }}-macos.dmg --clobber
        env:
          GH_TOKEN: ${{ github.token }}
